name: amica
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  shared_preferences:
  provider:
  intl:
  url_launcher:
  webview_flutter:
  image_picker:
  http:
  readmore:
  scrollable_positioned_list:
  cached_network_image:
  firebase_auth:
  firebase_core:
  flutter_secure_storage:
  google_sign_in:
  flutter_dotenv:
  onesignal_flutter:
  socket_io_client:
  timeago:
  flutter_markdown_plus:
  app_links:
  share_plus:
  path_provider:
  flutter_staggered_grid_view:
  shimmer:
  flutter_launcher_icons:
  flutter_cache_manager:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - source/images/
    - source/
    - .env

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true

  image_path: "source/images/icon_app_with_background.png"

  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "source/images/icon_app_no_background.png"